export const testimonials = [
  // Indian Customers (10)
  {
    id: 1,
    name: 'Priya Sharma',
    location: 'Delhi, India',
    rating: 5,
    text: 'The peacock green vastra I bought for my Laddu Gopal is absolutely beautiful! The quality is exceptional and the embroidery is so detailed. My little Krishna looks divine in it.',
    image: '/hero/peckok.jpeg',
  },
  {
    id: 2,
    name: 'Rajesh Kumar',
    location: 'Mumbai, India',
    rating: 4.5,
    text: 'Amazing collection of mukut! The copper crown I purchased is perfect for my deity. The craftsmanship is outstanding and it arrived in perfect condition.',
    image: '/hero/peckok.jpeg',
  },
  {
    id: 3,
    name: 'Sunita Devi',
    location: 'Varanasi, India',
    rating: 4.5,
    text: 'I have been buying from Balgopaal Vastram for over a year now. Every product is handcrafted with such love and attention to detail. Highly recommended!',
    image: '/hero/peckok.jpeg',
  },
  {
    id: 4,
    name: 'Amit Singh',
    location: 'Pune, India',
    rating: 5,
    text: "The bansuri I bought has such a beautiful sound! It's perfect for our daily prayers. The quality and the traditional craftsmanship is truly remarkable.",
    image: '/hero/peckok.jpeg',
  },
  {
    id: 5,
    name: 'Kavita Patel',
    location: 'Ahmedabad, India',
    rating: 5,
    text: 'Fast delivery and excellent customer service. The vastra collection is so beautiful and the colors are exactly as shown. My Laddu Gopal looks so elegant!',
    image: '/hero/peckok.jpeg',
  },
  {
    id: 6,
    name: 'Vikram Reddy',
    location: 'Hyderabad, India',
    rating: 5,
    text: 'The size guide was very helpful in choosing the right size for my deity. The products are authentic and the packaging is beautiful. Will definitely order again!',
    image: '/hero/peckok.jpeg',
  },
  {
    id: 7,
    name: 'Ramesh Kumar',
    location: 'Chennai, India',
    rating: 4.5,
    text: 'Amazing service and quick delivery. The products are of excellent quality and the packaging is beautiful. My family is very happy with the purchase!',
    image: '/hero/peckok.jpeg',
  },
  {
    id: 8,
    name: 'Deepak Kumar',
    location: 'Bengaluru, India',
    rating: 5,
    text: 'The golden mukut I ordered is simply stunning! The attention to detail is incredible and it fits my Laddu Gopal perfectly. Highly satisfied!',
    image: '/hero/peckok.jpeg',
  },
  {
    id: 9,
    name: 'Pooja Devi',
    location: 'Jaipur, India',
    rating: 4.5,
    text: 'Beautiful silk vastra with intricate work! The colors are vibrant and the fabric is so soft. My little Krishna looks like a prince in it.',
    image: '/hero/peckok.jpeg',
  },
  {
    id: 10,
    name: 'Arjun Mehta',
    location: 'Kolkata, India',
    rating: 5,
    text: 'Outstanding quality and beautiful designs! The peacock feather mukut is a masterpiece. The customer service team was very helpful with size selection.',
    image: '/hero/peckok.jpeg',
  },
  
  // International Customers (5)
  {
    id: 11,
    name: 'Sarah Johnson',
    location: 'New York, USA',
    rating: 5,
    text: 'I was amazed by the quality of these devotional items! The craftsmanship is incredible and the attention to detail is remarkable. My Krishna looks divine!',
    image: '/hero/peckok.jpeg',
  },
  {
    id: 12,
    name: 'Michael Chen',
    location: 'Toronto, Canada',
    rating: 4.5,
    text: 'Beautiful products with authentic Indian craftsmanship! The shipping was fast and the packaging was excellent. Will definitely order more items.',
    image: '/hero/peckok.jpeg',
  },
  {
    id: 13,
    name: 'Emma Williams',
    location: 'London, UK',
    rating: 5,
    text: 'Absolutely stunning collection! The silk vastra I bought is of the highest quality. The traditional designs are so beautiful and authentic.',
    image: '/hero/peckok.jpeg',
  },
  {
    id: 14,
    name: 'David Rodriguez',
    location: 'Sydney, Australia',
    rating: 4.5,
    text: 'Excellent service and beautiful products! The bansuri flute has such a melodious sound. The traditional craftsmanship is truly impressive.',
    image: '/hero/peckok.jpeg',
  },
  {
    id: 15,
    name: 'Lisa Anderson',
    location: 'Dubai, UAE',
    rating: 5,
    text: 'Outstanding quality and beautiful designs! The peacock green vastra is absolutely gorgeous. The embroidery work is so detailed and perfect.',
    image: '/hero/peckok.jpeg',
  },
]